[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-devkitc-1 ; Standard target for S3 variants
framework = arduino
monitor_speed = 115200

; Automated dependency tracking for your sensor suite
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    SPI
    Wire